name: dorker
description: A wrapper for Web Worker, one that allow you to have the worker's code in the same project.
version: 0.3.0
homepage: https://github.com/yuan-kuan/dorker
author: kuan <yuankuan@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.0
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
