name: dorker
description: A wrapper for Web Worker, one that allow you to have the worker's code in the same project.
version: 0.1.1
homepage: https://github.com/yuan-kuan/dorker
author: kuan <yuankuan@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  meta: ^1.1.6

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
