name: dorker
description: A wrapper for Web Worker, one that allow you to have the worker's code in the same project.
version: 0.2.0
homepage: https://github.com/yuan-kuan/dorker
author: kuan <yuankuan@gmail.com>

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  js: ^0.6.1+1
  meta: ^1.1.7

dev_dependencies:
  test: ^1.6.3
  build_runner: ^1.7.1
  build_web_compilers: ^1.2.2
